---
title: "Harvard Course Enrollment Graphic"
author: "Mike Silva"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

```{r library dowloads}
library(tidyverse)
library(readxl)
library(janitor)
library(fs)
library(ggthemes)

```

```{r loading data }
#I first downloaded the file using the url from the
#website

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx", 
              destfile = "enrollment2019.xlsx", 
              mode = "wb")

#read the data

x.2019 <- read_xlsx("enrollment2019.xlsx", skip= 3) %>%

#made the data table easier to work with
  
  clean_names() %>%

#removed NA's from data table and removed all courses with 
#more than 47 graduate students in order to remove all of 
#the courses with 100% graduate students because my graphic
#was extremely messy and elongated beforehand
  
  filter(! is.na(course_name)) %>%
  filter(grad < 47) %>%
  
#also removed all the courses offered that nobody enrolled in
  
  filter(total != 0) %>% 
  
#isolated the variables that I need to complete my graph  
  
  select(u_grad2019 = u_grad, course_department2019 = course_department, total2019 = total, grad2019 = grad)

#remove file from directory once the data is loaded

file_delete("enrollment2019.xlsx")

```

```{r code for graphic}
#start with plotting a scatter plot graph with each
#medical science class offered in spring 2019

p0 <-
  
#subsetting the data set here allows me to filter for
#just medical sciences, which is the department that
#offers the most courses in the semester
  
  ggplot(data = subset(x.2019,
                       course_department2019 == "Medical Sciences"),
         
#the total number of students enrolled int each
#course is on the x axis and the percentage of
#grad students is the y axis which creates a
#nice looking plot
         
         mapping = aes( x = total2019,
                        y = grad2019/100,
                        
#used the course department as the color in order for 
#the legend to show which department is which color
                        
                        color = course_department2019))

p1 <-
  
#added the scatter plot with a log scale on the
  #x axis to make it clearer to see and changed
  #the y label to percentages
  
  p0 + geom_point(alpha = 0.6) + scale_x_log10()  + 
                  
#messed around with this function until I found
  #a color scheme that fit well with the theme
  
  scale_color_brewer(palette = "RdylGn")

p2 <- 
  
#added another scatter plot replicating the previous code
#but filtered for the second most offered course department
  
  p1 + geom_point(alpha = 0.8, data = subset(x.2019,
                                course_department2019 == "Romance Languages & Lit"),
                  mapping = aes(x = total2019,
                                y = grad2019/100,
                                color = course_department2019))

p3 <- 
  
#repeated this code one more time with economics as the course
#department because it is the third most offered department
  
  p2 + geom_point(alpha = 1.0, data = subset(x.2019,
                                             course_department2019 == "Economics"),
                  mapping = aes( x = total2019,
                                 y = grad2019/100,
                                 color = course_department2019))


p4 <- 
  
#added a percentage label to the y axis using the scales package briefly
#and added all necessary labels
  
  p3 + scale_y_continuous(labels=scales::percent) +
    labs(color = "Course Department",
         x = "Class Size (log scale)",
         y = "Percent of Graduate Student Population",
         
#debated where to separate the title for a second line for
#a while and decided this was the cleanest way based on
#word size
         
         title = "Spring 2019 Student Disitribution \nby Course Department",
         caption = "Source: Harvard Registrar")

#messed around with different themes and this one worked well with my graphic

theme_set(theme_economist())

#used this function to edit the text size of all of my labels
#which makes everything look cleaner

p4 + theme(legend.text = element_text(size = rel(0.75)),
           plot.title = element_text(size = rel(1.75)),
           legend.title = element_text(size = rel(0.75)),
           plot.caption = element_text(size = rel(.75))) 
```

